### ISSUE TITLE
Springless trigger won't register, even with digital triggers enabled

### ISSUE THREAD

**Issue by CoinBahd** [Struggleton/Delfinovin#24] opened 2022-07-12 11:19 UTC
Is there a way to make Delfinovin ignore the analog input and only register the digital input, similar to how it would on Wii VC? My controller with 1 spring removed is not registering trigger inputs (on R), while it does work in Dolphin and Wii VC.

**Comment by Struggleton** [comment] 2022-07-20 05:08
Duplicate of #23 - please continue discussion there

**Closed by Struggleton** 2022-07-20 05:08 UTC
Labels: bug
